[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2024"
rust-version = "1.90"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.1", features = [] }
tauri-plugin-log = "2"
axum = "0.8.9"
tokio = { version = "1.53.2", features = ["full", "macros", "rt"] }
reqwest = { version = "0.13.5", features = ["stream"] }
rusty_ytdl = "0.7.4"
tower-http = { version = "0.7.1", features = ["cors", "set-header"] }
include_dir = "0.7.4"
mime_guess = "2.0.5"
