name: Build Desktop Apps

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build & Compile TypeScript
      run: npx tsc
      
    - name: Build Electron App
      run: npx electron-builder --${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'win' || 'mac' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ClipEditor-${{ runner.os }}
        path: |
          dist/*.exe
          dist/*.dmg
          dist/*.AppImage
